### ISSUE TITLE
New code with Keyerror

### ISSUE THREAD

**Issue by dljzx** [dabasajay/Image-Caption-Generator#2]
I tried your new code but got keyerror like this
Traceback (most recent call last):
File "train_val.py", line 15, in 
X1train, X2train, max_length = loadTrainData(config)
File "E:\github\Image-Caption-Generator\utils\load_data.py", line 186, in loadTrainData
train_image_features = load_image_features(config['model_data_path']+'features_'+str(config['model_type'])+'.pkl', train_image_ids)
File "E:\github\Image-Caption-Generator\utils\load_data.py", line 78, in load_image_features
features = {_id: all_features[_id] for _id in ids}
File "E:\github\Image-Caption-Generator\utils\load_data.py", line 78, in 
features = {_id: all_features[_id] for _id in ids}
KeyError: '172092461_a9a9762e13'
Can you help me again?

**Comment by dabasajay** [comment]
That error is occurring because of image id "172092461_a9a9762e13", which isn't present in your features_vgg16.pkl (or features_inceptionv3.pkl if you selected inceptionv3 model in config). This may happen because of **incomplete** processing of all of the images in the CNN model. Delete the features_vgg16.pkl (or features_inceptionv3.pkl) file from `model_data` folder and try again and make sure all ~8091 images are preprocessed using the CNN model to generate features for all images.

In case you don't want to do it yourself because of resources or anything, email me at **se.dabasajay@gmail.com** and I'll send you the direct link of pkl files I've already preprocessed.

Attaching a screenshot of what the process should look like.

![example](https://user-images.githubusercontent.com/38384266/58978122-d22f7a00-87e8-11e9-9d87-b7b67af0a552.png)
